[tool.poetry]
name = "hypermodern-python"
version = "0.1.0"
authors = ["Cheng Li"]
description = "The hypermodern Python project"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cli99/hypermodern-python"
repository = "https://github.com/cli99/hypermodern-python"
keywords = ["hypermodern"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
